name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag the Docker image
      run: |
        IMAGE_NAME=ghcr.io/jdawson1024/toxcity-api
        VERSION=$(date +%Y%m%d%H%M%S)
        # Build and tag the image with both VERSION and latest
        docker build . --file Dockerfile --tag $IMAGE_NAME:$VERSION --tag $IMAGE_NAME:latest

    - name: Push the Docker image
      run: |
        IMAGE_NAME=ghcr.io/jdawson1024/toxcity-api
        VERSION=$(date +%Y%m%d%H%M%S)
        # Push both VERSION and latest tags
        docker push $IMAGE_NAME:$VERSION
        docker push $IMAGE_NAME:latest
